# Generated by Django 5.2.17 on 2026-09-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('kicker', models.CharField(blank=True, help_text='Small label shown above the title, e.g. the organization name.', max_length=200)),
                ('mission_statement', models.TextField(blank=True, help_text='Shown under the title on the public registration page.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, help_text='Groups this question under a section heading. Leave blank to continue the previous section.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_type', models.CharField(choices=[('text', 'Short text'), ('email', 'Email'), ('phone', 'Phone'), ('number', 'Number'), ('textarea', 'Long text'), ('boolean', 'Yes / No'), ('single_choice', 'Single choice'), ('multi_choice', 'Multiple choice'), ('repeatable_group', 'Repeatable group')], max_length=20)),
                ('label', models.CharField(max_length=300)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('required', models.BooleanField(default=False)),
                ('depends_on_value', models.CharField(blank=True, max_length=200)),
                ('show_in_insights', models.BooleanField(default=False, help_text='Show an answer-distribution bar chart for this question on the dashboard.')),
                ('quick_filter', models.BooleanField(default=False, help_text='Add a quick-filter pill for this question on the dashboard (best for Yes/No questions).')),
                ('depends_on', models.ForeignKey(blank=True, help_text="Only show this question if depends_on's answer equals depends_on_value.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='events.eventquestion')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.event')),
                ('parent_question', models.ForeignKey(blank=True, help_text='Set only for a sub-question that repeats inside a Repeatable group question.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='events.eventquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('secondary_label', models.CharField(blank=True, help_text='Optional right-aligned tag, e.g. a time shown next to a schedule option.', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='events.eventquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('attendee_count', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_index', models.PositiveIntegerField(default=0, help_text='Which repetition this belongs to, for sub-questions of a repeatable group.')),
                ('value_text', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='events.eventquestion')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='events.registration')),
            ],
            options={
                'ordering': ['repeat_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_index', models.PositiveIntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='events.eventquestionoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='events.eventquestion')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='events.registration')),
            ],
            options={
                'ordering': ['repeat_index', 'id'],
            },
        ),
    ]
