# Generated by Django 5.2.17 on 2026-09-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquestion',
            name='show_in_table',
            field=models.BooleanField(default=False, help_text='Give this question its own column in the dashboard table (kept short — best for Yes/No or repeatable-group counts).'),
        ),
    ]
