# Generated by Django 5.2.17 on 2026-09-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventquestion_show_in_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquestion',
            name='short_label',
            field=models.CharField(blank=True, help_text='Compact label for dashboard stat cards, filter pills, and table columns (falls back to a truncated label).', max_length=60),
        ),
    ]
