# Generated by Django 5.2.17 on 2026-09-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventquestion_short_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Full-bleed photo behind the hero title. Falls back to a plain navy background if blank.', null=True, upload_to='events/hero_backgrounds/'),
        ),
        migrations.AddField(
            model_name='event',
            name='hero_title_image',
            field=models.ImageField(blank=True, help_text='Stylized title artwork shown in the hero, in place of the plain event title text. Optional.', null=True, upload_to='events/hero_titles/'),
        ),
    ]
