# Generated by Django 5.2.17 on 2026-09-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_hero_background_image_event_hero_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_notice_body',
            field=models.TextField(blank=True, help_text='Body text for the registration-deadline notice box. Falls back to a generic sentence if blank.'),
        ),
    ]
