# Generated by Django 5.2.17 on 2026-09-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_registration_notice_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_notice_highlight',
            field=models.CharField(blank=True, help_text='Optional phrase appended to the notice body in gold, e.g. "September 30." — for emphasizing a deadline.', max_length=200),
        ),
    ]
