# Generated by Django 5.2.17 on 2026-09-15 16:44

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_registrationattempt'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('event'), name='unique_registration_per_event_email'),
        ),
    ]
