# Generated by Django 5.2.17 on 2026-09-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_registration_unique_registration_per_event_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquestion',
            name='quick_filter_sums_attendees',
            field=models.BooleanField(default=False, help_text='Only used when quick_filter is on. Show total headcount (this registration\'s attendee count plus anyone listed in a repeatable group, e.g. children) across matching registrations, instead of just counting matching registrations. Turn on for headcount-planning questions like meals; leave off for things like "first time visitor?" where a household count is what you actually want.'),
        ),
    ]
