# Generated by Django 5.2.17 on 2026-09-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventquestion_quick_filter_sums_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquestion',
            name='counts_as_attendees',
            field=models.BooleanField(default=False, help_text='Repeatable-group questions only. Turn on when each row in this group is a person who should count toward headcount stats (e.g. "list each child"). Leave off for repeatable groups that aren\'t people (e.g. "list each allergy") — otherwise their row count would get added to attendee totals.'),
        ),
    ]
