# Generated by Django 5.2.17 on 2026-09-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventquestion_counts_as_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(blank=True, help_text='Organization tagline shown under the mission statement on every event\'s registration page, e.g. "ARISE. BUILD. COMPEL". Leave blank to hide it.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
