# Generated by Django 5.2.17 on 2026-09-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_seed_site_settings_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admission_text',
            field=models.CharField(blank=True, default='Free Admission', help_text='Shown as a pill in the About section, e.g. "Free Admission" or "$10 at the door".', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='quote_attribution',
            field=models.CharField(blank=True, help_text='Attribution for the quote above, e.g. "ELLEN G. WHITE, THE ADVENTIST HOME, p. 15.1".', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='quote_text',
            field=models.TextField(blank=True, help_text='Inspirational quote shown in the About section, e.g. an Ellen G. White quote.'),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.TextField(blank=True, help_text='One speaker per line, shown as pills in the About section, e.g. "Devaney & Fazlyn Haupt".'),
        ),
    ]
