# Generated by Django 5.2.17 on 2026-09-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_admission_text_event_quote_attribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Soft-cancel: set by staff instead of deleting, so the record and its answers are kept.', null=True),
        ),
    ]
