# Generated by Django 5.2.17 on 2026-09-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_registration_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquestion',
            name='placeholder',
            field=models.CharField(blank=True, help_text='Custom placeholder text for a text/email/phone/number field\'s input. Leave blank for the generic default (e.g. "Short answer").', max_length=100),
        ),
    ]
