# Generated by Django 5.2.17 on 2026-09-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_eventquestion_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquestion',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number-type questions only. When set, the form shows a live running total next to this field (this answer times cost per unit), e.g. $10 per meal.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='eventquestion',
            name='payment_link_label',
            field=models.CharField(blank=True, help_text='Button text for payment_link_url, e.g. "Pay for Meals".', max_length=60),
        ),
        migrations.AddField(
            model_name='eventquestion',
            name='payment_link_url',
            field=models.URLField(blank=True, help_text='Optional payment/action link shown under this question, e.g. a PayPal donate link.'),
        ),
    ]
